# Nueva solicitud de cambio

## Tipo de cambio
<!-- Marque con una X ( De esta manera [ X ] ) -->
[ ] Corrección/Nueva guía
[ ] Ajuste de desarrollo

## Descripción
<!-- Describa brevemente el cambio realizado -->


### ¿Informó sobre el cambio?
<!-- Marque con una X ( De esta manera [ X ] ) -->
[ ] Sí, fue recibido por los encargados (Privado, Servidor de contribución)
[ ] No / Ninguna de las anteriores