blank_issues_enabled: false
contact_links:
  - name: ✏️ Servidor de Contribución
    url: https://discord.gg/2jJRNbyqMB
    about: Entra al servidor de contribución e infórmate con lo que necesites
  - name: 📁 Servidor Principal
    url: https://discord.gg/doofy-s-projects-704042607600205956
    about: Asegurate de leer la información del servidor