name: Guias
description: Sugiere la adición de nuevas guías en la documentación.
title: "[Guía]: "
labels: ["Guías"]
body:

  - type: dropdown
    id: tipoG
    attributes:
      label: Categoría de guía
      description: Selecciona la categoría a la cual va dirigida la guía.
      options:
        - Instalación
        - Información
        - Optimización
        - Errores
    validations:
      required: true

  - type: input
    id: discordG
    attributes:
      label: Usuario de Discord
      description: Detalla aquí la información de tu usuario en Discord.
      placeholder: Diso#1693 (ID:379375263022317584)
    validations:
      required: true

  - type: textarea
    id: contenidoG
    attributes:
      label: Contenido de la guía
      description: Tienes este espacio para redactar tu guía.
      placeholder: Recuerda que este espacio soporta la sintaxis Markdown.
    validations:
      required: true