name: Mejoramiento
description: Colabora con el mejoramiento general o especifico de la página y su entorno.
title: "[Guía]: "
labels: ["Mejoramiento"]
body:

  - type: dropdown
    id: tipoM
    attributes:
      label: Tipo de mejoramiento
      description: Selecciona la dirección que toma el mejoramiento que indicas.
      options:
        - Tipografía u ortografía
        - Codigo
        - Otros
    validations:
      required: true

  - type: input
    id: discordM
    attributes:
      label: Usuario de Discord
      description: Detalla aquí la información de tu usuario en Discord
      placeholder: Diso#1693 (ID:379375263022317584)
    validations:
      required: true

  - type: textarea
    id: contenidoM
    attributes:
      label: Contenido del mejoramiento
      description: Específica en este espacio el porqué de tu idea y cómo podría realizarse.
      placeholder: Recuerda que este espacio soporta la sintaxis Markdown.
    validations:
      required: true